<?xml version="1.0" encoding="UTF-8"?>
<!--
 ........................................    &&&&&&&&&&&&&&&    ................................ 
 .......................................  ;&&:            +$&&   ............................... 
 ......................................  &&   ...........    .&&  .............................. 
 .....................................  &x  ..:................$&   ............................ 
 .................................... .&...............:..:::....&X  ........................... 
 ...................................  & .......................: .&: ........................... 
 ................................... &$     ..   ......          .&& ........................... 
 ................................... &..+&&&&&&&$Xx...:x&&&&&&&&. X&  .......................... 
 ..................................  & .:       .::...;;.      ;&..&  .......................... 
 ..................................  & .;+&$&&&&$+;..:xXX$&&&&&;x;.&  .......................... 
 ..................................  & .:X&xx+++..;;:;;:::..;X$;...&  .......................... 
 .................................. .& .. ..::. .::...:;....    ...&  .......................... 
 .................................. X& :.........       .......:...&& .......................... 
 .................................. $& ......+x+X&&XX&&&$x;.......;&& .......................... 
 .................................. &$ ::..:X...        ...:;:.:;:;&+ .......................... 
 .................................. ...:+++X:  .;+;.:xx+:. :x;:x+:;$;........................... 
 ....................................;+:;;:.x&&$:::..  .;&&x;..$.;x$..::.:.:.................... 
 ....................................:X;:...+$  .::.++&&&&$...:+ x&$.....:...::................. 
 .................................... :X::....:XXXX;;;xXX;... +.:&  .::..:::.:.:................ 
 ..................................... &X:;.........:....... :+;&& :::..:::.:.:::::............. 
 .....................................  &+:;.:::.:;:;::...;..++$& .:.::;:::.::....::............ 
 ...................................... &$+:::..:;:...;:..;;xX&$& ..::::::::::::::::............ 
 ...................................    +x$$;;:.          X&&&x+$   .::::::::::::::::........... 
 ...............................     X&$;;;X&$$XX++x$&&&&&&$Xxx+Xx&.     ..:::::.::::........... 
 ............................    .&&&  $x::;x&&&&&&&&&&&&$$xx++x$X+&&&&x    .:::::::;........... 
 .......................      &&&&&&   &+::.::::x&&&&&&$$$XXXXXX&  &&$&&&&&.   .::;:;:.......... 
 ....................    .&&&&&$Xx$&X   X+...;x+..     .::;+: :$   &$x$X$$&&&X    ..:: ......... 
 ................     $&&&&$x+X$xXx&&&   Xx:..:+xx++xxx+:....;x   &&x$&XXX$$$&&&x   .:.......... 
 ..............   .&&&&XxxxX$XXXX$$X$&&:   ;;:....:;:::.::::.   &&&X$XX$XXXXXX$$&&&x    ........ 
 .............  .&&&$XXXX$xXxXXXXxx$$X&&&&     ..:;+:;;:.     &&&&X$$xX$$$$XXX$XX$&&&&.    ..... 
 ............  &&$XX$$X$XXX&$$XxXX$XX$$X$&&&&&&:         x&&&&&$$X$$$$$XX$$$$XXXXXX$&&&&&x  .... 
 ...........  $&&XX$$XX$XXXXXxXXx+xxxxX$&&x+X&&&&&&&&&&&&&&$XX$&&$$XxXXXxxXxx$x+$XxxXX$&&&&   .. 
 ..........  ;&&&&X&$$X$$Xxx$X$X$$&&&XXXx$&&&$X$$XX$XxX$&$&&&&$$XxX$&$$$&$X$X$$$$$$$XXX$X$&&   . 
 .......... .&&&$X$$XXXXX$$&&$$&&&$$&$X$$$$&&$X$X$X&&$$xxXx+xxx+X$XXXXXXXXX$$XX$XXX$$&XX&&$&&:   
 .........  &&$&$X$&&$$$$$XXxXXXxXxX&&xxx$xxx$$&XXXXX$$&&&&XXxxx$&$&&$$$$$XXXXX$$XXXXX+X$XX$&&   
 ......... &&X$&&xX$$$$XX$$$$XXxXXXX+X$&XXXXXxXXxXX$XXXxX$$$&&&$$$XXx$$&XXX$&$X&$X$&&$$$$$$&&&&  
 ........  &&XxX$$$X$X$$xXxX$$&&X$XX&&X&&&&X&$$$X$$X$$x$XxX$XxX$X$xXXXxX&&XXXXXXxX$$&$X$$$$&X&&  
 ........ .&$$X$$$XXXX$$$&$XXXxx$XXx+xxxxxXXXX$XXXxx$XXX$$&$$$XXxXX$$$$$X$$$$$XX$&&$X$$$$$$&$$&& 
 .......  &&$XXX$$XXXXX$$$$$$X$$$XX$$$$$XXxX$XxxXXXXX$$$x$$X$XX$&&$$$Xx$$XXXX$$$$$XX$$$&$X$$&&&& 
 ....... .&X$XXX$$X$$&$X$$$$$$$&$X$XX&X$$$XX&XXX$$XXXxX&XXXX$$XX$XxXX$$XX$$$$$$XXxX$$$$$X$$$&&&&.
 ......  X&$X$XxXx$$X$X$$$XXXXxXXXXXX$xxXXXXXXX&$X&&&$$x$&xx$X$XXXX$X$$$$X$$$$$$X&&&$&&&&$$$&$X&:
 ...... .&&$XXXx&&&$XxxXx$$$&$XXX+XXXX&$XXXX$XxxxXxXXX&$&&XX$X$$$$$$X$$X$$$$xX$$X$$$$$&&$X&$&$&$.
 .....  &&XX$&XXX$X+;;+++xxxX$&$$$XX$&$$X$$Xx$&&$X$$$Xx$xxX$X$&XXXX$$&X$XX$$$&&$&&$X&&&$x$&X$XXX:
 .....  &$$$X$XxX&&&&&&&&&X$xxXXXxX$X$X$$&$xX$Xx$XxX$XxX$$X$X$$$$&$XXXX$$XXX&$X$$$$$&&xXX&&XX$&&;
 ....  &&$XX$$&&$xX&&&+X$&$$&&XXX$$XXx$$$X$X&$X$X$&&$$&$XX$$$XXX$XX$$$&&X$&$XXX$$&&&&&+$$XXX$$X$:
 ...  +&$XX$XXXxXXXX&$+$$X$$$$$$$$XX$$X$$$XxXXX$$XXX$XXXXxXXX$&$X$$X$XX$$XX$$$$$&&&&&&&&&&&$&&XX.
 ..  &&&&&$X$XXX$$$$&$&X$$&$$$$$XX$&$$XX$$&&&$$XX$&&xX$&&&&$$xX$X$X$&$X$$$$$X&&&&     &&&&&&$$$$;
 .. .&&$$$$XX&&&&&&&&.&xXX$X$$X$$X$$$$$XX$$xX$&&$$X$$$XxxxX$$$X$X$$XXX$&$$&$$X&&+ :;.  &&&&$&$XX:
    &&$$X$$$$$$&&&&&: &$$&XX$$X$$$&XxX$$$$X$&XXXXXX$$$X$$x$$XXXxXXXXX$XX$$$$$&&$ :++;;   &&&&&&&$
  :&&&&$$XXX$X$&&&&&  &&$X$&$$$xxxx$$$$$X$$&&$&$$$$&X$$&&&&XX$$$&$$$$$$X$$$X&&& .;;;;;;:  &&&&&&X
  X&&XXX$&$&&&&&&&&.  &&XX$&$&&$&&$$X$$$$$xXX$X$$X$&XXX$xx$&$&$XxxXXXX$$$X&&&&: ;;++;;;+:. &&&&&&
  X;:::;;;+++xxxX$x    $+;;::;;::.:::.:::::::..:::.:::::..::::::::;::+++XX$$$;                  x
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.comunicacao</groupId>
	<artifactId>api</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>api</name>
	<description>Gateway publico da arquitetura de microsservicos</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
